files, = glob_wildcards("data/{sample}.fastq.gz")




include: "rules/ncrna_workflow.smk"



rule all:
	input:
		expand("results/count_tables/{gene}.tsv",gene=gene),
		expand(["results/count_tables/" + x + ".tsv" for x in ["lncRNA","misc_RNA","protein_coding","snoRNA","snRNA","scaRNA"]]),
		"results/file_statistics.csv",
		expand("analyses/fastqc/{sample}.trimmed.FastQC/{sample}.trimmed_fastqc.zip",sample=files),
		"results/multiqc_report.html",
		"results/mirtrace/mirtrace-report.html"




