files, = glob_wildcards("data/{sample}.fastq.gz")




include: "rules/ncrna_workflow.smk"



rule all:
	input:
		expand("results/count_tables/{gene}.tsv",gene=gene),
		expand(["results/count_tables/" + x + ".tsv" for x in ["lincRNA","misc_RNA","protein_coding","snoRNA","snRNA","scaRNA","antisense"]]),
		"results/file_statistics.csv",
		expand("analyses/stats/{sample}.trimmed.FastQC",sample=files)


